services:
  simulator:
    build: .
    container_name: simulator
    command: python /app/mock/main.py
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  celery_server_worker:
    build: .
    container_name: celery_server_worker
    command: celery -A server worker --pool=solo --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://


  # celery_cupom_worker:
  #   build: .
  #   container_name: celery_cupom_worker
  #   command: celery -A cupom worker --loglevel=info --pool=solo
  #   volumes:
  #     - .:/app
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest@rabbitmq//
  #     - CELERY_RESULT_BACKEND=rpc://
  #   depends_on:
  #     - rabbitmq